<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>erb</string>
		<string>rhtm</string>
		<string>rhtml</string>
	</array>
	<key>foldingStartMarker</key>
    <string>(?x)
(&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|li|form|dl)\b.*?&gt;
|&lt;!--(?!.*--\s*&gt;)
|^&lt;!--\ \#tminclude\ (?&gt;.*?--&gt;)$
|&lt;\?(?:php)?.*\b(if|for(each)?|while)\b.+:
|\{\{?(if|foreach|capture|literal|foreach|php|section|strip)
|\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
)</string>
    <key>foldingStopMarker</key>
    <string>(?x)
(&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|li|form|dl)&gt;
|^(?!.*?&lt;!--).*?--\s*&gt;
|^&lt;!--\ end\ tminclude\ --&gt;$
|&lt;\?(?:php)?.*\bend(if|for(each)?|while)\b
|\{\{?/(if|foreach|capture|literal|foreach|php|section|strip)
|^[^{]*\}
)</string>
	<key>injections</key>
	<dict>
		<key>text.html.erb - (meta.embedded.block.erb | meta.embedded.line.erb | comment)</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^\s*)(?=&lt;%+#(?![^%]*%&gt;))</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.erb</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)(\s*$\n)?</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.trailing.erb</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^\s*)(?=&lt;%(?![^%]*%&gt;))</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.embedded.leading.erb</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)(\s*$\n)?</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.embedded.trailing.erb</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tags</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tags</string>
				</dict>
			</array>
		</dict>
	</dict>
	
	<key>keyEquivalent</key>
	<string>^~H</string>
	<key>name</key>
	<string>HTML (Ruby - ERB)</string>
	<key>patterns</key>
	<array>
	 <dict>
            <key>begin</key>
            <string>(?:^\s+)?(&lt;)((?i:style))\b(?![^&gt;]*/&gt;)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.html</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.style.html</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)((?i:style))(&gt;)(?:\s*\n)?</string>
            <key>name</key>
            <string>source.css.embedded.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-stuff</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(&gt;)</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.tag.end.html</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>(?=&lt;/(?i:style))</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.css</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
		 <dict>
            <key>begin</key>
            <string>(&lt;)((?i:script))\b(?![^&gt;]*/&gt;)(?![^&gt;]*(?i:type.?=.?text/((?!javascript|babel).*)))</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.html</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.script.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=&lt;/(script|SCRIPT))(&gt;)(?:\s*\n)?</string>
            <key>endCaptures</key>
            <dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.html</string>
                </dict>
            </dict>
            <key>name</key>
            <string>source.js.embedded.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-stuff</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;!&lt;/(?:script|SCRIPT))(&gt;)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.tag.begin.html</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.script.html</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>(&lt;/)((?i:script))</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>captures</key>
                            <dict>
                                <key>1</key>
                                <dict>
                                    <key>name</key>
                                    <string>punctuation.definition.comment.js</string>
                                </dict>
                            </dict>
                            <key>match</key>
                            <string>(//).*?((?=&lt;/script)|$\n?)</string>
                            <key>name</key>
                            <string>comment.line.double-slash.js</string>
                        </dict>
                        <dict>
                            <key>begin</key>
                            <string>/\*</string>
                            <key>captures</key>
                            <dict>
                                <key>0</key>
                                <dict>
                                    <key>name</key>
                                    <string>punctuation.definition.comment.js</string>
                                </dict>
                            </dict>
                            <key>end</key>
                            <string>\*/|(?=&lt;/script)</string>
                            <key>name</key>
                            <string>comment.block.js</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>source.js</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
		 <dict>
            <key>begin</key>
            <string>(&lt;)([a-zA-Z0-9:-]++)(?=[^&gt;]*&gt;&lt;/\2&gt;)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.html</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(&gt;)(&lt;)(/)(\2)(&gt;)</string>
            <key>endCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.html</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.html meta.scope.between-tag-pair.html</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.html</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.html</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.html</string>
                </dict>
            </dict>
            <key>name</key>
            <string>meta.tag.any.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-stuff</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>(&lt;\?)(xml)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.html</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(\?&gt;)</string>
            <key>name</key>
            <string>meta.tag.preprocessor.xml.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-generic-attribute</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#string-double-quoted</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#string-single-quoted</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>&lt;!--</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>--\s*&gt;</string>
            <key>name</key>
            <string>comment.block.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>--</string>
                    <key>name</key>
                    <string>invalid.illegal.bad-comments-or-CDATA.html</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>&lt;!</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>&gt;</string>
            <key>name</key>
            <string>meta.tag.sgml.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>(?i:DOCTYPE)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.doctype.html</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>(?=&gt;)</string>
                    <key>name</key>
                    <string>meta.tag.sgml.doctype.html</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>match</key>
                            <string>"[^"&gt;]*"</string>
                            <key>name</key>
                            <string>string.quoted.double.doctype.identifiers-and-DTDs.html</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>\[CDATA\[</string>
                    <key>end</key>
                    <string>]](?=&gt;)</string>
                    <key>name</key>
                    <string>constant.other.inline-data.html</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(\s*)(?!--|&gt;)\S(\s*)</string>
                    <key>name</key>
                    <string>invalid.illegal.bad-comments-or-CDATA.html</string>
                </dict>
            </array>
        </dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;%+#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.erb</string>
						</dict>
					</dict>
					<key>end</key>
					<string>%&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.erb</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.erb</string>
				</dict>
			</array>
		</dict>
		<key>tags</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;%+(?!&gt;)[-=]?(?![^%]*%&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.erb</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.ruby</string>
					<key>end</key>
					<string>(-?%)&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.erb</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.ruby</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.erb</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.erb</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(#).*?(?=-?%&gt;)</string>
							<key>name</key>
							<string>comment.line.number-sign.erb</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.ruby</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;%+(?!&gt;)[-=]?</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.erb</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.ruby</string>
					<key>end</key>
					<string>(-?%)&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.erb</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.ruby</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.line.erb</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.erb</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(#).*?(?=-?%&gt;)</string>
							<key>name</key>
							<string>comment.line.number-sign.erb</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.ruby</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.erb</string>
	<key>uuid</key>
	<string>13FF9439-15D0-4E74-9A8E-83ABF0BAA5E7</string>
</dict>
</plist>